<?php

function w3s_boot() {
  set_include_path(get_include_path() . PATH_SEPARATOR . dirname(__FILE__) . DIRECTORY_SEPARATOR . 'library');
  $funcs = spl_autoload_functions();
  foreach ($funcs as $autoload_function) {
    spl_autoload_unregister($autoload_function);
    spl_autoload_register('w3s_autoloader');
    foreach ($funcs as $autoload_function) {
      spl_autoload_register($autoload_function);
    }
  }
}

function w3s_init(){
  if(!drupal_session_started()){
    drupal_session_start();
  }
}
/*
 * Add the w3s_autoloader to the autoloader registry
 */

function w3s_autoloader($classname) {

  $path = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'library';
  $file = str_replace('_', DIRECTORY_SEPARATOR, $classname) . '.php';
  $filename = $path . DIRECTORY_SEPARATOR . $file;

  if (file_exists($filename)) {
    require_once $filename;
  }
}

function w3s_menu() {
  $items = array();
  return $items;
}

function w3s_get_arg($param, $args = null) {
  if (null === $args) {
    $args = explode('/', $_GET['q']);
  }
  if (!in_array($param, $args)) {
    return false;
  }
  if (isset($args[array_search($param, $args) + 1])) {
    $value = $args[array_search($param, $args) + 1];
    return $value;
  }
  return true;
}

